services:
  postgres:
    image: postgres:16
    container_name: smart-meal-postgres
    environment:
      POSTGRES_DB: smart_meal_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - smart-meal-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smart_meal_service"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  smart-meal-postgres-data:
